GET http://localhost:3000/places?text=Rua julior araujo cavalcante, Camaragibe, 57

###
GET http://localhost:3000/places?text=Rua das Rosas, 15 - Bairro Novo do Carmelo

###
@originId = ChIJcavkgEMaqwcRluyOYjzm6eQ
@destinationId = ChIJySuhEUYaqwcRjppOS-CR16E

###
GET http://localhost:3000/directions?originId={{ originId }}&destinationId={{ destinationId }}

###
POST http://localhost:3000/routes
Content-Type: application/json

{
    "name": "rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

###
GET http://localhost:3000/routes

###
GET http://localhost:3000/routes/675a6d967d9eecf3765a997b